---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
# Install library
list_of_packages <- c('lattice', 'xts', 'miscTools')
new_packages <- list_of_packages[!(list_of_packages %in% installed.packages()[,'Package'])]
if(length(new_packages)) install.packages(new_packages, repos="http://cran.rstudio.com/")
library(lattice)
library(xts)
library(miscTools)

# Read File
unzip("activity.zip", overwrite = TRUE)
dataset_complete <- read.csv(
    "activity.csv", 
    na.strings = "NA", 
    stringsAsFactors=FALSE, 
    header = TRUE
)

dataset_complete$date <- strptime(dataset_complete$date, "%Y-%m-%d")
dataset_complete$dateFactor <- cut(dataset_complete$date, breaks="days")
```

## What is mean total number of steps taken per day?
```{r}
# Ignore NA and 0 Steps
dataset <- dataset_complete[!is.na(dataset_complete$steps),]
# dataset <- dataset[!dataset$steps == 0,] --- Removing 0's throw more meaningfull results
# in pretty much every graph. As that wasn't requested I left this commented. 
# Uncomment to see better Histogram, median and mean results.

# Draw Histogram
histogram(
    dataset$steps ~ dataset$dateFactor, 
    xlab='Days', 
    ylab='Steps', 
    main="Total steps taken per day"
)

# Prepare Steps Time Series
steps.xts <- xts(dataset$steps, dataset$date)

# Steps Mean
steps_means <- apply.daily(steps.xts, colMeans)
plot(steps_means, main="Mean of steps per day")
steps_means

# Steps Median
steps_medians <- apply.daily(steps.xts, colMedians)
plot(steps_medians, main="Median of steps per day")
steps_medians
```

## What is the average daily activity pattern?

```{r}
mean_steps_across_intervals <- aggregate(
    dataset$steps ~ dataset$interval, 
    dataset, 
    mean
)

names(mean_steps_across_intervals) <- c("interval","steps")

plot(
    mean_steps_across_intervals$interval, 
    mean_steps_across_intervals$steps,
    type="l",
    main="Average number of steps taken by daily interval",
    xlab='Interval',
    ylab='Avg Steps'
)

max_steps_by_interval <- mean_steps_across_intervals[
    mean_steps_across_intervals$steps == max(mean_steps_across_intervals$steps)
    ,]

out <- paste(
    "Interval ", max_steps_by_interval$interval,
    " contains the maximum average"," of steps accros all the days. ",
    sep=""
)

print(out)
```

## Imputing missing values
```{r}
# Calculate missing Values
dataset_na <- dataset_complete[is.na(dataset_complete$steps),]
out <- paste("There are ", nrow(dataset_na), 
             " rows with no data in the dataset", 
             sep=""
)
print(out)

# Fill missing values with Mean of steps by interval
dataset_complete_to_fill <- dataset_complete

#dataset_complete_to_fill$steps[dataset_complete_to_fill$steps == 0] <- NA

for(i in 1:nrow(dataset_complete_to_fill))
{
    if(is.na(dataset_complete_to_fill[i,]$steps) || dataset_complete_to_fill[i,]$steps == 0) {
        steps <- mean_steps_across_intervals[
            mean_steps_across_intervals$interval == dataset_complete_to_fill[i,]$interval,
        ]$steps
        if(length(steps) > 0){
            dataset_complete_to_fill[i,]$steps <- steps            
        }
    }
}

histogram(
    dataset_complete_to_fill$steps ~ dataset_complete_to_fill$dateFactor, 
    xlab='Days', 
    ylab='Steps', 
    main="Total steps taken per day using NA"
)

```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
##df1$date <- as.Date(df1$date)
#create a vector of weekdays
##weekdays1 <- c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')
#Use `%in%` and `weekdays` to create a logical vector
#convert to `factor` and specify the `levels/labels`
##df1$wDay <- factor((weekdays(df1$date) %in% weekdays1), 
##         levels=c(FALSE, TRUE), labels=c('weekend', 'weekday') 
#Or
##df1$wDay <- c('weekend', 'weekday')[(weekdays(df1$date) %in% weekdays1)+1L]
```

